### ISSUE TITLE
Make simplification tolerance configurable

### ISSUE THREAD

**Issue by apezel** [t-rex-tileserver/t-rex#102]
The option simplify = true is very useful but there's no way to set the level of simplification. To prevent visual artifacts during zooming i think it may be useful in some cases to snap geometries to a finest grid. (for example pixel_width / 4). I can contribute and make a PR if needed.

**Comment by pka** [comment]
You are absolutely right. The current hardcoded value of pixel_width/2 should be configurable. Do you have an idea how this configuration should look like? `simplify = "!pixel_width!/4"`? A PR is always welcome!

**Comment by pka** [comment]
Yes, makes sense.

**Comment by pka** [comment]
Implemented by PR #103
