### ISSUE TITLE
Panic because of missing geometry_type field in config file

### ISSUE THREAD

**Issue by frodrigo** [t-rex-tileserver/t-rex#106]
I got this error using my own config file with the last Docker release.
```
thread 'arbiter:a27bf9bd-deaf-4a95-9ca6-9c1f04d96079:actor' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
```

I try to compile without the release param to get an error log, but I fail. I can't build nor directly, not using Dockerfile.

**Comment by frodrigo** [comment]
I got it. The `geometry_type` field was missing in the config file.

**Comment by pka** [comment]
A better message is returned since 2f1fb4f. Time for a new release!
