### ISSUE TITLE
Error 'Too many features have accumulated in points layer'

### ISSUE THREAD

**Issue by pierrebonbon** [t-rex-tileserver/t-rex#108]
I got t-rex running and it serves the small `liechtenstein-latest.osm.pbf` dataset well. However, when trying to serve anything larger such as the whole North American dataset, it does seem to (very, very slowly) render the data. I also get the following error: `ERROR 1: Too many features have accumulated in points layer. Use OGR_INTERLEAVED_READING=YES mode`.

This is what I'm typing on the command line: `t_rex serve --bind 0.0.0.0 --openbrowser=true --datasource north-america-latest.osm.pbf`

I wonder what I'm doing wrong, if anything? Or should I throw more hardware at it? I'm currently running a 8 Dedicated X86 64bit Cores, 32GB memory server.

**Comment by pka** [comment]
Looks like we have to set OGR_INTERLEAVED_READING=YES in the OGR driver of t-rex. But I think a big PBF extract will always be too slow.
You could either convert to a faster file based format with ogr2ogr (https://www.gdal.org/drv_osm.html) or import the PBF into PostGIS (osm2psql, imposm, etc.)

**Comment by pierrebonbon** [comment]
Thank you so much for the prompt reply and input. I will try your last suggestion and will . Btw, do you have any suggestions regarding a faster file to convert to?

**Comment by pka** [comment]
e.g. https://www.gdal.org/drv_geopackage.html

**Comment by pierrebonbon** [comment]
Thanks, will look into it and report!

**Comment by pierrebonbon** [comment]
Converting the `PBF` to `gpkg` worked just fine, ~75B in size (filtered for some of the features and without metadata). Still attempting to import the same filtered PBF into PostGIS to compare performance but it should be fine. In other words, not an issue with t-rex specifically but with feeding a fast format, as suggested. Please feel free to close this issue if you see fit. Ohh and thanks a lot for pointing me in the right direction!

**Comment by pka** [comment]
Thanks for the feedback!
