### ISSUE TITLE
Invalid vector tiles according to spec

### ISSUE THREAD

**Issue by nimix** [t-rex-tileserver/t-rex#115]
Right now there are a few problems that might occur in t-rex generated vector tiles, because of the transformation to screen coordinates.

1. There might be repeated points because different coordinates are rounded to the same screen coordinate. This violates 4.3.3.2 of the 2.0 vector tile spec:

> For any pair of (dX, dY) the dX and dY SHOULD NOT both be 0

2. 4.3.4.3: States that a LINESTRING needs at least one LineTo command:

> A LineTo command with a command count greater than 0

3. A valid ring need at least 4 points 4.3.4.4:

> 1. A MoveTo command with a command count of 1
> 2. A LineTo command with a command count greater than 1
> 3. A ClosePath command

4. The outer ring of a polygon needs to be in clockwise winding order and inner rings in counter clockwise winding order. This rule is sometimes violated because rings might turn when transformed to screen coordinates.

5. Transformation to screen coordinates might introduce self intersections or intersections between different inner/outer rings of a polygon.

**Comment by pka** [comment]
Thanks a lot for the PR! Do you have any test data for the mentioned cases?
