### ISSUE TITLE
Database pool size is not respected

### ISSUE THREAD

**Issue by cazgp** [t-rex-tileserver/t-rex#119]
The database connection pool config parameter doesn't seem to be respected.

Test case:

1. `psql -c 'SELECT COUNT(*) FROM pg_stat_activity'`
6
1. Set `pool` to `20`.
1. Run `t_rex`.
1. `psql -c 'SELECT COUNT(*) FROM pg_stat_activity'`
86

This makes sense because https://github.com/t-rex-tileserver/t-rex/blob/13d7fc353fa15c2cbe5443c50860e16a076cf6f0/t-rex-core/src/datasource/postgis.rs#L614 has a TODO around the fact the database size is hard-coded to 10, and `t_rex` runs num CPU workers = 8 on this machine. So 10*8 = 80.

However, there should be one database pool which every worker uses. So possibly this is two issues: the config isn't respected, and each worker is given its own pool.

```
$ t_rex --version
t_rex 0.9.1 (GDAL version 2.3.2)
```

**Comment by pka** [comment]
Since version 0.9.0 each process has its own connection pool. `pool` should at least set the size of each pool, or even better set the total size.

**Comment by dmitrykinakh** [comment]
Do we have any progress here? In the project, I run we have faced by with an issue when Trex server eat all available connections to DB (we are using Amazon RDS instance) so any other app can't connect to it.

**Comment by pka** [comment]
Improvements of the DB connection pool are postponed after a major update to actix-web 1.0 (which should be released soon) has happened. This update will also include initializing the DB connection pool before spawning web server processes.

**Comment by dmitrykinakh** [comment]
but at the same time, could you help me to understand what is the purpose of having this set to 10 per thread?

For now, I'm running these two generate commands on my server:
```
t_rex generate --tileset tx_property_records --overwrite true --minzoom 14 --maxzoom 19 --extent -97.2709,32.5636,-96.1929,33.0731 --config /storage/trex/XXXXX.toml;'

t_rex generate --tileset tx_street --overwrite true --minzoom 14 --maxzoom 19 --extent -97.2709,32.5636,-96.1929,33.0731 --config /storage/trex/XXXXX.toml;'
```

and each of them adding 10 connections to DB where only one from 10 is working with DB:
![image](https://user-images.githubusercontent.com/8025637/57064802-21592b00-6cd0-11e9-9eb7-52e281228e86.png)

**Comment by pka** [comment]
Shared connection pool is implementented in master branch.
