### ISSUE TITLE
Threads doesn't seem to be respected

### ISSUE THREAD

**Issue by cazgp** [t-rex-tileserver/t-rex#120]
Test:

1. Set threads to "1" in config.
2. Run t_rex.
3. Output in console:

```
2019-03-02 17:46:06.762 INFO Starting 8 workers
```

Does this parameter control the number of workers or is that something different?

Using v0.9.1.

**Comment by pka** [comment]
Since 1.9.0 the number of workers is automatically set to the available CPU cores. This is a good default, but `threads` should override this default again.

**Comment by pka** [comment]
Implemented in master.
