### ISSUE TITLE
Awesome Tool - Anyway to Improve Cache Generation Time?

### ISSUE THREAD

**Issue by reyemtm** [t-rex-tileserver/t-rex#121]
Awesome tool, got it running in no time on Ubuntu 18. One issue is the cache generation speed. Overall time is not an issue at under 2 minutes for a 3MB geojson, but this seems slow compared to my current method using geojson-vt in node. The file is in WGS84. I do get a log warning of unknown field type when it is serving. I will try with another file that does not log any errors and report results. The reprojecting to 3857 may also be a factor...

**Comment by pka** [comment]
For PostGIS data, parallel seeding mode is quite effective. With 4 cores you can run something like

    t_rex generate --config mvtbench.toml --progress=false --nodes=4 --nodeno=0 &
    t_rex generate --config mvtbench.toml --progress=false --nodes=4 --nodeno=1 &
    t_rex generate --config mvtbench.toml --progress=false --nodes=4 --nodeno=2 &
    t_rex generate --config mvtbench.toml --progress=true  --nodes=4 --nodeno=3

Parallization of a single file is probably less effective

**Comment by reyemtm** [comment]
Ok, good to know. Will test this method and report back.
