### ISSUE TITLE
Impossible to generate tiles

### ISSUE THREAD

**Issue by diouck** [t-rex-tileserver/t-rex#125]
I impoer data 200m / 200m squared on the whole France. When I start the data trimming the server does nothing for 24 hours. Whereas if I limit the data to 10,000 objects it works. Do you have an idea or encounter this problem? Or is there a size limits objects to generate?
Thank you

**Comment by pka** [comment]
The record count limit is just to improve the performance, it's not a technical limit. It usually doesn't make sense to have so many objects in a single tile. If you run t-rex with a different log level you should see which query takes so long.
