### ISSUE TITLE
Which field type needs to be used to have an array field in PSQL

### ISSUE THREAD

**Issue by dmitrykinakh** [t-rex-tileserver/t-rex#140]
Is there a way to create an array field in PostgreSQL so Trex will understand it properly?
Right now we do that in this way:
![image](https://user-images.githubusercontent.com/8025637/63519714-18e56400-c4fc-11e9-9aae-d50dbb952b2e.png)

But when we generate the tiles we have this warning 
`2019-08-22 13:34:41.753 WARN Layer 'fl_land_use_city': Converting field 'place' of type _text to TEXT`
and then in generated PBF we have a text instead of an array:

![image](https://user-images.githubusercontent.com/8025637/63519840-4e8a4d00-c4fc-11e9-96cb-1aba70787cd4.png)

Is there a way how we can tell Trex that place column is an array?

**Comment by pka** [comment]
The Mapbox [MVT spec](https://github.com/mapbox/vector-tile-spec/tree/master/2.1) has no array value types. What mapping between a PostgreSQL array column and an MVT layer would you expect?

**Comment by dmitrykinakh** [comment]
Well, in this case, how can I filter by multiple values in the multivalued field?

Imagine you have a table in DB like showed on my screen above. Where one row has several values for place column. How do I need to set up a filter, in this case, to be able seach by 2-3 values? The example below doesn't work for me.
`{
  "id": "fl_land_use_code",
  "type": "fill",
  "source": "fl_land_use_city",
  "source-layer": "fl_land_use_city",
  "filter": [
    "match",
    [
      "get",
      "place"
    ],
    [
      "fl-state-place-12086",
      "fl-state-place-1270075",
      "fl-state-place-33154"
    ],
    true,
    false
  ],
  "layout": {
    "visibility": "visible"
  },
  "paint": {
    "fill-color": [
      "match",
      [
        "get",
        "title"
      ],
      "PU",
      "hsla(100, 100%, 45%, 0.75)",
      "BZ",
      "hsla(316, 100%, 45%, 0.75)",
      "PD-1",
      "hsla(287, 99%, 49%, 0.75)",
      "PD-2",
      "hsla(287, 100%, 33%, 0.75)",
      "PD-3",
      "hsla(287, 96%, 19%, 0.75)",
      "C-1",
      "hsla(7, 100%, 50%, 0.75)",
      "C-2BE",
      "hsla(0, 100%, 23%, 0.75)",
      "C-2BW",
      "hsla(0, 100%, 75%, 0.75)",
      "C-3",
      "hsla(350, 100%, 87%, 0.75)",
      "M-1",
      "hsla(0, 0%, 51%, 0.75)",
      "R-1",
      "hsla(60, 100%, 87%, 0.75)",
      "R-2",
      "hsla(60, 100%, 50%, 0.75)",
      "R-4",
      "hsla(60, 100%, 30%, 0.75)",
      "R-5",
      "hsla(40, 100%, 48%, 0.75)",
      "R-6",
      "hsla(40, 100%, 33%, 0.75)",
      "RO",
      "hsla(100, 100%, 23%, 0.75)",
      "TOD",
      "hsla(214, 86%, 75%, 0.75)",
      "None",
      "hsla(332, 31%, 50%, 0.75)",
      "hsla(169, 91%, 33%, 0.45)"
    ],
    "fill-opacity": [
      "interpolate",
      [
        "exponential",
        1
      ],
      [
        "zoom"
      ],
      0,
      1,
      22,
      1
    ],
    "fill-outline-color": "rgba(154, 154, 154, 0.45)"
  }
}`

**Comment by dmitrykinakh** [comment]
I don't think it can be resolved here.
