### ISSUE TITLE
Can't load libssl on platforms with libssl.1.1

### ISSUE THREAD

**Issue by rapadu** [t-rex-tileserver/t-rex#154]
Libssl.so.1.0.0. is no longer available. 

`t_rex: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
`

**Comment by pka** [comment]
Thanks for reporting. Which platform/distribution are you woking on ?

**Comment by rapadu** [comment]
Right now for development reasons I use Ubuntu 19.04 / 19.10. The package Libssl.so.1.0.0 
is no more maintained in the repos. I tried to link libssl.so.1.0.0 to libssl.1.1 but then T_Rex won't start

**Comment by rburkat** [comment]
Any resolution to this.  I'm using debian buster and have ran into the same issue.
t_rex serve --config config.toml
t_rex: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by pka** [comment]
A new package will come together with #201

**Comment by pka** [comment]
With the release of v0.11.0 there are now packages for Debian Buster and Ubuntu Focal: https://github.com/t-rex-tileserver/t-rex/releases

**Comment by azhe403** [comment]
i've download `t-rex-v0.13.0-x86_64-linux-gnu.tar.gz` and got this error

`./t_rex: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
