### ISSUE TITLE
Using S3 to cache the generated tiles

### ISSUE THREAD

**Issue by kicmultimedia** [t-rex-tileserver/t-rex#169]
Hi.

We are looking to use S3 to cache the tiles generated rather than local storage. I saw you were looking into this and has been on the roadmap since 2017. Is this something that will be a possibility within the near future?

**Comment by pka** [comment]
Yeah, that was always on top of the roadmap. But since I never needed it myself and no customer project / funding happened, it's still on the wait list...

**Comment by kicmultimedia** [comment]
What would it take in funding to get this built in?

**Comment by pka** [comment]
Can you contact me directly (for mail see https://github.com/pka)?

**Comment by arbakker** [comment]
Hi, do you have an update on this issue? We are also looking to use t-rex to cache tiles on s3, so I am curious whether any progress was made.

**Comment by pka** [comment]
Still on the wish list...

**Comment by arbakker** [comment]
Thanks for the update! For now our workaround suffices, but that will change probably.

**Comment by pka** [comment]
Thanks @arbakker for implementing this! Ready for testing in master...
