### ISSUE TITLE
QGIS Integration: Support HTTP HEAD

### ISSUE THREAD

**Issue by sebastian-r-schmidt** [t-rex-tileserver/t-rex#179]
I'm trying to integrate t-rex-tileserver as backend to QGIS Desktop via the vector tiles reader Plugin available via http://plugins.qgis.org/plugins/vector_tiles_reader/.

When Connecting to t-rex, a URL pointing to style.json and tiles.json files is needed in the 
Vector Tiles Plugin. While connecting to t-rex that plugin sends HTTP HEAD requests to those URLs in order to check if they exist.

Unfortunately, t-rex answers with HTTP 404 when doing a HEAD reqeust on those URLS.
(see: https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/blob/dev-qgis3/plugin/util/network_helper.py, line 12).

Which turns t-rex unreachable from that pluign.

Doing a hack, i patched VTR Plugin to do a classic HTTP GET, and further integration looks fine then, I can display vector tiles data inside QGIS.

Question: is it possible to implement HTTP HEAD for those tile.json and style.json Resources?

**Comment by pka** [comment]
That should be quite easy. Sounds like a good first PR... I will probably work more on t-rex in January.
