### ISSUE TITLE
Trex does not generate empty pbf

### ISSUE THREAD

**Issue by dmitrykinakh** [t-rex-tileserver/t-rex#194]
![image](https://user-images.githubusercontent.com/8025637/77430465-ec702e00-6de3-11ea-85b8-2734c25c9d25.png)

On my screen, you can see that there is only 1 building showed in the middle of the screenshot.
Due to data missed for the rest of the map, I'm getting a lot of 404 errors and I'm not quite sure if that is right. Should not Trex still generate pbf even it's empty?

**Comment by pka** [comment]
Does #96 explain your problem?
