### ISSUE TITLE
how to run T-rex on Mac os

### ISSUE THREAD

**Issue by manhcuongincusar1** [t-rex-tileserver/t-rex#195]
any one tell how to run t-rex on Mac os?

**Comment by pka** [comment]
The "official" way to use t-rex on Mac is via Docker: https://t-rex.tileserver.ch/doc/setup/

There is also a binary for Mac, but this one is tested on Travis CI only: https://github.com/t-rex-tileserver/t-rex/releases/tag/v0.10.1

**Comment by manhcuongincusar1** [comment]
thanks a lot!
