### ISSUE TITLE
Messed tiles from PostGIS line data

### ISSUE THREAD

**Issue by manhcuongincusar1** [t-rex-tileserver/t-rex#196]
Hi! Any body have idea for that

**i got some troubles with generating vectortiles from postgis source, this is the result:**
<img width="1892" alt="Screen Shot 2020-04-09 at 7 48 18 PM" src="https://user-images.githubusercontent.com/63287450/78898190-9a92fd80-7a9d-11ea-999f-60bb56ab723e.png">

**it is supposed to be like that (which generated by direct shp file):**
<img width="1919" alt="Screen Shot 2020-04-09 at 8 07 51 PM" src="https://user-images.githubusercontent.com/63287450/78898324-cf06b980-7a9d-11ea-9b4a-8fc8ad3f707c.png">

**Comment by manhcuongincusar1** [comment]
this is my config file:

`# t-rex configuration

[service.mvt]
viewer = true

[[datasource]]
dbconn = "postgresql://postgres@localhost/t_rex"
name = "dbconn"
default = true

[grid]
predefined = "wgs84"

[[tileset]]
name = "thua"
extent = [106.66611, 10.78822, 106.69245, 10.81412]
[[tileset.layer]]
name = "thua"
table_name = "thua"
geometry_field = "geom"
geometry_type = "LINESTRING"
srid = 4326
buffer_size = 0
#make_valid = true
simplify = true
query_limit = 1000
#[[tileset.layer.query]]
#sql = """SELECT geom,id,10_id FROM thua WHERE geom && !bbox!"""

#[cache.file]
#base = "/tmp/mvtcache"
#baseurl = "http://example.com/tiles"

[webserver]
# Bind address. Use 0.0.0.0 to listen on all adresses.
bind = "127.0.0.1"
port = 6767

#[[webserver.static]]
#path = "/static"
#dir = "./public/"`

**Comment by pka** [comment]
How do your PostGIS data look in QGIS and what SRS do they have?

**Comment by manhcuongincusar1** [comment]
this my Postgis in Qgis: with SRS is EPSG 4326
<img width="1918" alt="Screen Shot 2020-04-10 at 10 36 44 AM" src="https://user-images.githubusercontent.com/63287450/78960116-43317380-7b17-11ea-94f9-983120803bdc.png">

**Comment by pka** [comment]
You're producing tiles in Web-Mercator Grid (EPSG 3857), right? Then I suggest to transorm your data to EPSG 3857 before feeding them into t-rex. This makes it also a lot faster.

**Comment by pka** [comment]
I've tested your dataset with the latest t-rex version and there is still the same strange result!

The reason seems to be the 3D geometry handling. After dropping the Z coordinate, the tiles look fine.

With on-the-fly reprojection:
```
ogr2ogr -f PostgreSQL PG:dbname=trextests -nln thua -dim XY thua/10.shp
```
Looks ok, only simplificaton doesn't work well.

With reprojection on import:
```
ogr2ogr -f PostgreSQL PG:dbname=trextests -nln thua_merc -dim XY -t_srs EPSG:3857 thua/10.shp
```
Looks fine.

The dataset:
```
ogrinfo -al -so thua/10.shp
INFO: Open of `thua/10.shp'
      using driver `ESRI Shapefile' successful.

Layer name: 10
Metadata:
  DBF_DATE_LAST_UPDATE=2019-11-08
Geometry: 3D Line String
Feature Count: 100276
Extent: (106.666114, 10.788225) - (106.692453, 10.814119)
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
10_ID: Integer (5.0)
```
