### ISSUE TITLE
Support nested objects and arrays for properties in feature

### ISSUE THREAD

**Issue by Blesss** [t-rex-tileserver/t-rex#197]
Hello.
Mapbox [doesn't have a native array, json value type support in vector tiles.](https://github.com/mapbox/vector-tile-spec/blob/2242b503e14a98c79b423fe7d398c1a1f3597e91/2.1/vector_tile.proto#L19)
As a workaround, each value from a list (column with an array data type in psql) could be stored as a property key:

```
“properties“: {
   "id": 123123,
   "Doral": 1,
   "Fort Myers Beach": 1,
   "Fort Lauderdale": 1
}
```

and to filter in Mapbox gl we can use "has" operator:
```
"filter": [
    "any",
      [
        "has",
        "Fort Myers Beach"
      ],
      [
        "has",
        "Fort Lauderdale"
      ],
    ]
```
I see that now it's not possible to configure t-rex to have such feature structure in case we have a column with an array data type in psql.

Is there any way to achieve that now?

**Comment by pka** [comment]
If there is a limited set of additional properties, they could be added as fields with an SQL query. Or are there a lot of these "any" properties?

**Comment by Blesss** [comment]
There are a lot of unique (a few thousand), but for one feature there will be no more than 15 and in the filter, it will be 1-2. We already tried to add new columns for each type of place - City, Commission District,  County, Neighborhood, Town,... but that covers only partial our needs because 1 item can belong to multiple places of the same type (E.g. zip code).

**Comment by pka** [comment]
So the proposal is to array columns as as addional attributes, right? Would also adding key/values of hstore (+json?) columns make sense?

**Comment by Blesss** [comment]
Yes, that is my proposal. What I'm thinking about is that attributes keys should contain a column name. So that, we can have multiple array data columns and know to which column an attribute belongs. The same logic can be used for json.

“properties“: {
   "id": 123123,
   "%column_name.%array value or json key": some value,
   "%column_name..%array value or json key": some value,
   "%column_name..%array value or json key": some value
}

**Comment by Blesss** [comment]
I think that could be closed. Support for array data type was added.
