### ISSUE TITLE
libgdal20 not available for Ubuntu20.04

### ISSUE THREAD

**Issue by Nachtmeer** [t-rex-tileserver/t-rex#201]
Hello,

I'm trying to install a t-rex server at Ubuntu20.04, but it seems that the libgdal20 package is not available any maybe replaced by libgdal26? Is there a way to install t-rex at Ubuntu20.04?

**Comment by pka** [comment]
Oh, sorry, missed this one. Docker seems to be the only option on a system with libgdal26 currently. But there there is a new release planned in June, which will include an updated package.

**Comment by pka** [comment]
With the release of v0.11.0 there are now also packages for Debian buster and Ubunto focal: https://github.com/t-rex-tileserver/t-rex/releases
