### ISSUE TITLE
T-rex deployment on heroku

### ISSUE THREAD

**Issue by ricmenol** [t-rex-tileserver/t-rex#215]
Hi,
Is there some report of deploy of the t-rex on heroku platform?
I have knowledge heroku doesn't have builtin support to Rust apps but I found this buildpack (https://github.com/emk/heroku-buildpack-rust) that seems allow this deployment.
Could you take a quick look just to check if t-rex could work in that context?
Thank you for your attention.

**Comment by pka** [comment]
I think it's about 10 years ago, when I did some work with Heroku. But if there is PostGIS support in the meantime, it looks like a good fit! I would propose to build t-rex without GDAL dependency (`cargo build --no-default-features ...`).

**Comment by ricmenol** [comment]
Thank you for your answer. At this moment there is support up to the Postgis 2.5 on Heroku so indeed a good match to deploy with t-rex.
I will build it without the GDAL dependency and try to deploy with heroku-buildpack_rust.
Best regards.
