### ISSUE TITLE
Configuration file documentation

### ISSUE THREAD

**Issue by pnorman** [t-rex-tileserver/t-rex#22]
I can't find any documentation on the configuration, just an example at https://github.com/pka/t-rex#configuration

I'm mainly interested in tileset.layer and tileset.layer.query, what properties can be set, and what their meanings are.

**Comment by pka** [comment]
A homepage containing more documention is in the works. Still not happy with favicon design (#23) and more ..

**Comment by pka** [comment]
-> https://t-rex.tileserver.ch/doc/reference/

**Comment by gismatthew** [comment]
I am still clueless about how to expose attributes/properties. It is unfortunate that such an important feature is never documented.
Can anyone show me how to achieve this? I'm publishing a `gpkg` file and I suppose it should be defined as part of the layer's query but it does not work. Here is my config:
```
[[tileset.layer.query]]
minzoom = 0
sql = """
    SELECT geom, 'FIELD1' as name
    FROM MY_LAYER_IN_GPKG
    WHERE geom && !bbox
"""
```

**Comment by pka** [comment]
As documented in the `query` section of https://t-rex.tileserver.ch/doc/reference/#tileset , SQL queries are supported only for PostGIS data sources. For Geopackages all attributes are published by default.
