### ISSUE TITLE
New image on Docker Hub for v0.12.0

### ISSUE THREAD

**Issue by emacgillavry** [t-rex-tileserver/t-rex#221]
Still pulling in v0.11.0 from Docker Hub. What would be involved in getting the latest T-Rex ? Many thanks!

**Comment by pka** [comment]
Completely forgot about updating the der Docker container, after switching the CI provider. Will do that very soon.

**Comment by pka** [comment]
Docker image 0.12.0 is  now available.

**Comment by emacgillavry** [comment]
Wow! Thanks for the quick turn-around.
