### ISSUE TITLE
vector tiles probe on geohealthcheck

### ISSUE THREAD

**Issue by pvgenuchten** [t-rex-tileserver/t-rex#269]
Recently a probe to test vector tiles tilejson landed in [geohealthcheck](https://geohealthcheck.org/). Did one of you test Latest T-Rex with this probe?

I tested an [older version](https://tiles.isric.org) of T-Rex and it fails on a missing tilejson key, which indeed is required according to [mapbox spec](https://github.com/mapbox/tilejson-spec/tree/master/2.0.0). 

Does T-Rex actually follows the mapbox spec, or some alternative tilejson spec? 

Thanx for the great work here!

**Comment by pka** [comment]
Interesting service! I never tested T-Rex tiles this way, but the goal is to follow the Mapbox spec.

I couldn't find a way to test a service myself with the the geohealthcheck demo instance. An example of a recent public service would be https://adv-smart.de/tiles/smarttiles_de_public_v1/smarttiles_de_public_v1.json

**Comment by pvgenuchten** [comment]
![image](https://user-images.githubusercontent.com/299829/143258963-770bd424-fb48-4747-be9c-4ee35b897a5b.png)

use the mapbox tilejson service, it is available on demo.geohealthcheck.org

**Comment by pvgenuchten** [comment]
the service-url provided indeed fails with same error:

![image](https://user-images.githubusercontent.com/299829/143263583-962cbd02-cdd7-4a51-85ae-ef4f6701d47a.png)

t-rex tilejson-file does not have a property tilejson, as suggested by tilejson spec:
![image](https://user-images.githubusercontent.com/299829/143263923-8d303f89-0674-45c7-9b1f-99fed322acfb.png)

**Comment by pka** [comment]
Ah, thanks! Will use it to fix tilejson conformance.
