### ISSUE TITLE
Is there a way to drop old tiles where geometry is not present anymore?

### ISSUE THREAD

**Issue by dmitrykinakh** [t-rex-tileserver/t-rex#270]
Hi there,
I have the following case.
1. Let's imagine I've tiled the boundary of every county in the world.
2. After a while, I've removed geometry data for the capital of Ukraine, Kyiv from DB.
3. From the Trex perspective, as far, as I for, no geometry - no requests to generate something for that area.
4. So, after regenerating tiles I might face the case, that on some zoom levels, (I think 0-10 or something like that), the shape of Kyiv will be not present as other capitals might be included in a single PBF file due to zoom, level. However, as soon as the area where Kyiv was located will be only the item that was in PBF - Trex will skip regeneration of those PBFs as no need to regenerate if there is no data in DB.

Please see  the video of the  case I'm referring to - https://monosnap.com/file/4gAoODHAVFbu2X7sPzha0IQk5snA85

Is there any other option (except add an extra flag in DB for those records (like deleted = 1) and then exclude records with that status from map view?

**Comment by pka** [comment]
There is the `--overwrite` flag in [t_rex generate](https://t-rex.tileserver.ch/doc/generate/#usage), but as you mention, empty tiles are not generated as files. There seems actually a need for an explicit delete operation. The only way for now is to delete genereted tiles manually and regenerate the cache.

**Comment by dmitrykinakh** [comment]
This issue was resolved in https://github.com/t-rex-tileserver/t-rex/pull/276
Closing.
