### ISSUE TITLE
 startup take too long time with many postgis tables

### ISSUE THREAD

**Issue by tarikcarli** [t-rex-tileserver/t-rex#284]
Hi all, I have a postgresql that contains lots of spatial tables and tables will continue to take place in my database. I have to dynamically add tables that added later to trex configuration and serve those tables. If I change trex configuration and restart tileserver, It took at least 3 minutes to be serve tiles. Is there a way to dynamically add table layer to trex without restart or any suggestion to overcome this issue.

**Comment by pka** [comment]
Automatic geometry detection can take a lot of time, when there are many tables. You can disable it with
```
t_rex serve --detect-geometry-types false ....
```

A long time enhancement wish is a schema/table filter for limiting geometry detection.
