### ISSUE TITLE
t-rex vs other MVT servers?

### ISSUE THREAD

**Issue by not-my-profile** [t-rex-tileserver/t-rex#293]
I am a bit confused by t-rex being an MVT server built on PostGIS but not using PostGIS' `ST_AsMVT` function. What is the reasoning behind that? Other PostGIS MVT servers like [Martin](https://github.com/maplibre/martin), [pg_tileserv](https://github.com/CrunchyData/pg_tileserv) and [Tegola](https://tegola.io/) apparently all use `ST_AsMVT`.

In #287 @xamanu implies that not using `ST_AsMVT` makes t-rex unsuitable for some kind of layers. Is that the case? If so for what kind of data can t-rex be used? The README just says that t-rex is specialized on publishing MVT tiles from "your own data" but does not mention any limitations.

**Comment by pka** [comment]
The main reason is that t-rex predates `ST_AsMVT` for years. Not using `ST_AsMVT` has some advantages and disadvantages. I've made a few presentations comparing vector tile servers. The last one in english was probably at FOSS4G 2021. Slides are available here: https://blog.sourcepole.ch/2021/09/29/foss4g-2021/
