### ISSUE TITLE
Error in loading vector tiles with standalone mapbox gl js viewer

### ISSUE THREAD

**Issue by Weltstaat** [t-rex-tileserver/t-rex#295]
Hi!

I have generated vector tiles from customized osm data with t_rex generate. Everything has worked fine and I'm able to display the tiles with the builtin t-rex viewers.

For testing and building my style I use the mapbox gl js offline viewer from klonkan (https://github.com/klokantech/mapbox-gl-js-offline-example). The viewer is able to read for example vector tiles created with tippecanoe. If I define the t-rex tiles as source however, I get the javascript error "Unimplemented type: 7" in the browser console. 

According to my websearching it may have something to do with the compression of the pbf's (see here: https://gis.stackexchange.com/questions/373922/using-pbf-vector-tiles-generated-with-t-rex-with-openlayers-errors-with-uncaug), but I still can't get it running.

Do you have any ideas?

Thanks!

**Comment by pka** [comment]
It's probably a missing `gzip` header as answered here: https://gis.stackexchange.com/a/373923
