### ISSUE TITLE
cargo build error for GDAL

### ISSUE THREAD

**Issue by pjanetzek** [t-rex-tileserver/t-rex#302]
Hello, I'm quite new to rust -  could you tell me where to  set  `--features bindgen` to make t-rex build?

```
  thread 'main' panicked at 'No pre-built bindings available for GDAL version 3.6. Use `--features bindgen` to generate your own bindings.',
```

Thanks!

**Comment by pjanetzek** [comment]
I can build gdal-sys with bindgen when checking it out on it's own.

**Comment by pjanetzek** [comment]
ok found the Cargo.toml
```
gdal-sys = { version = "0.8", features = ["bindgen"] }
```

**Comment by dotlambda** [comment]
> ```
> gdal-sys = { version = "0.8", features = ["bindgen"] }
> ```

@pka Could this be made the default?

**Comment by pka** [comment]
@dotlambda Done in master branch.

**Comment by dotlambda** [comment]
@pka That also has to be reflected in `Cargo.lock`.

**Comment by pka** [comment]
@dotlambda done
