### ISSUE TITLE
Better seperation of layer definitions and deployment information

### ISSUE THREAD

**Issue by pnorman** [t-rex-tileserver/t-rex#46]
I'm writing layer definitions I'd like others to be able to use, but the config files are a mix of layer definitions (tileset stuff) and deployment information like IP addresses (`[webserver]` stuff). It would be good to have these independent so I can distribute layer definitions without making too many assumptions about someone's configuration.

**Comment by pka** [comment]
Makes sense to me. What about an option `configdir` which holds partial TOML configurations?

**Comment by norac89** [comment]
Something like `include = ["datasource1.toml, layer1.toml, layer2.toml]` would be very useful in term of readability and reusability for complex configuration.

**Comment by pka** [comment]
With the new template support, the configuration can be split into mutlple files and variables can be passed via environment variables or in a .env file.
