### ISSUE TITLE
Fix invalid polygons after simplification, coord. transform or clipping

### ISSUE THREAD

**Issue by pka** [t-rex-tileserver/t-rex#5]
Some vector tile creation steps can produce invalid polygons:
- Simplification
- Coordinate transform
- Clipping (tile buffer)

See also https://github.com/mapbox/vector-tile-spec/issues/58#issuecomment-173717621 and https://github.com/tilezen/mapbox-vector-tile/issues/42#issue-142647621

**Comment by Wykks** [comment]
Indeed. I'm getting this

![image](https://user-images.githubusercontent.com/1236069/27226579-ff85c73c-529f-11e7-94b3-4e2c53b60e49.png)

Using these data https://raw.githubusercontent.com/gregoiredavid/france-geojson/v2-hd-dev/departements.geojson
Imported to postgis with 
`ogr2ogr -f PostgreSQL PG:"host=127.0.0.1 port=9500 dbname=postgres user=postgres password=test" departements.geojson -nln depts -s_srs EPSG:4326 -t_srs EPSG:3857`

**Comment by pka** [comment]
@Wykks buffer_size is now also generated for type GEOMETRY (eb895535)

**Comment by Wykks** [comment]
Actually, I don't know what's type `GEOMETRY`. T-rex generate config with this, but then it doesn't know what to do with it: 
`Error converting between Postgres and Rust types: Unknown geometry type GEOMETRY`.
It seems that t-rex is incorrectly detecting the geometry_type from postgis. 
QGIS detect the geometry_type POLYGON without issue, so I think that my datasource is fine.
