### ISSUE TITLE
Rendering artifacts, square tiles

### ISSUE THREAD

**Issue by skinkie** [t-rex-tileserver/t-rex#54]
I noticed that I get rendering artifacts in MapBox GL and OpenLayers. Is there a setting to prevent the "square tiles" here I mean the edge around them?

Mapbox GL
![bla](https://user-images.githubusercontent.com/502394/29537927-dd231962-86c3-11e7-8175-6148abcdf832.png)

OpenLayers
![bla1](https://user-images.githubusercontent.com/502394/29537946-f03ce15e-86c3-11e7-907a-4bd96d1a1784.png)

**Comment by pka** [comment]
I remember seeing tile borders before, but actually never investigated their cause. Can you give more information about your configuration? I think, I saw them with custom projections only.

**Comment by skinkie** [comment]
Hi @pka thanks for your fast feedback. I am basically evaluating multiple vector tile solutions, after tegola I tried t-rex (first couldn't get t-rex it to work, then was impressed by the webbased gui, and understood more). For tegola I created some materialized views with 3857 as projection. Which I resused in t-rex. My problems with tegola were basically rendering artifacts when zooming in Mapbox GL, which the Mapbox GL people referred as 'buffer-size' issues. My current problem with t-rex (next to the tiling borders) is that the generation is relatively slow, but when the browser is _not_ in developer mode, the client doesn't fetch / or is extremely slow in fetching the pbf files.

Part of the configuration is:
```
[service.mvt]
viewer = true

[datasource]
type = "postgis"
url = "postgresql://openov:s k i p p e d@localhost/openov"

[grid]
# Predefined grids: web_mercator, wgs84
predefined = "web_mercator"

[[tileset]]
name = "zoning"
#extent = [-180.0,-90.0,180.0,90.0]
[[tileset.layer]]
name = "zones"
table_name = "zones"
geometry_field = "wkb_geometry"
geometry_type = "POLYGON"
srid = 3857
fid_field = "zone_id"
simplify = true
buffer_size = 10
query_limit = 100000
[[tileset.layer.query]]
sql = """SELECT "wkb_geometry","zonenr","zone_id","zonenaam","nulzones" FROM ovzones_3857 WHERE wkb_geometry && !bbox!"""
```

The data is open, so if you want to have a pg_dump and the complete config to reproduce, I am happy to provide it.

**Comment by pka** [comment]
Sorry, I needed a break, but now back working on t-rex.

I've imported test data from http://data.openov.nl/zones/ like this:
`ogr2ogr -t_srs EPSG:3857 -unsetFieldWidth -nln ovzones_3857 -f PostgreSQL PG:dbname=natural_earth_vectors ovzones/ovzones01022016.shp`

I also get some artifacts, but my result is quite different. Can you describe your import or send me a dump (pg_dump -Fc) and the full config?

![grafik](https://user-images.githubusercontent.com/19007/30398098-6e733894-98cf-11e7-8797-37a500a2bb40.png)

**Comment by skinkie** [comment]
http://stefan.konink.de/trex.toml
http://stefan.konink.de/everything.sql.gz

**Comment by pka** [comment]
Looks better here:

![grafik](https://user-images.githubusercontent.com/19007/30400835-7ffdd836-98d8-11e7-84a1-676777eb11e4.png)

Are you sure, that there isn't a polygon layer with `buffer_size = 0` in your configuration? Because this would explain a border caused by polygon clipping.

**Comment by skinkie** [comment]
I do have an other configuration which has buffer_size = 0, what should that be?

**Comment by pka** [comment]
`buffer_size` is the additional pixel border around a tile. When clipping a polygon this buffer hides the clipped polygon outline.

![tileschema](https://user-images.githubusercontent.com/19007/30401471-b1d477d2-98da-11e7-927d-2e37efebcf56.png)

Maybe you've filled the cache with the other configuration?
