### ISSUE TITLE
unminified viewer.js

### ISSUE THREAD

**Issue by mbernasocchi** [t-rex-tileserver/t-rex#56]
hey @pka, more a question than an issue. 
I wanted to try to add some things on the default viewer but I could only find `t-rex/t-rex-webserver/src/static/viewer.js` which is a minified thing. do you have the non minified code somewhere?

cheers
Marco

**Comment by pka** [comment]
Just found it's new home: https://github.com/t-rex-tileserver/t-rex-viewer
