### ISSUE TITLE
Running t_rex from within a Docker container cannot connect

### ISSUE THREAD

**Issue by hunt3ri** [t-rex-tileserver/t-rex#59]
Hi 

Thanks for building the server, it's really cool.  I'm attempting to run the t_rex server from within docker but I can't connect to it from the host.

I suspect the problem is that the server runs on docker at 127.0.0.1:6767 but to make it connectable from the host it needs to run at 0.0.0.0:6767.  This is how I have to run uwsgi when I want to run my python apps within docker

Can you suggest how I can get t_rex to run on 0.0.0.0

Thanks

**Comment by pka** [comment]
Makes absolutely sense, but I could swear it worked for me...

**Comment by hunt3ri** [comment]
I'm completely prepared to believe I've made an elementary mistake.  However, I tried a few things with no success.

A config switch on the next release to specify the socket would be **awesome**.  Gunicorn calls the switch bind, and uwsgi http-socket.  Perhaps http-socket is the most descriptive.  Something like:

t_rex serve --dbconn postgresql://postgres:password@postgis/data-loader --http-socket 0.0.0.0:6767

**Comment by pka** [comment]
You _can_ configure the bind adress, but currently only in the configuration file: http://t-rex.tileserver.ch/doc/configuration/
It makes absolutely sense to expose this as a command line parameter.

**Comment by hunt3ri** [comment]
Ahhhhhhh I didn't see that config option right at the bottom of the config file 😄 

Tweaked it and now happily running t_rex from within docker.  It would be handy having it as a cli param though.

Thanks for the quick response.

**Comment by pka** [comment]
CLI options `bind` and `port` are added now and a Docker image is published.

Usage example:
```
docker pull sourcepole/t-rex
docker run -p 6767:6767 -v $(pwd):/var/data/in sourcepole/t-rex serve --bind=0.0.0.0 --openbrowser=false --datasource=t-rex-gdal/natural_earth.gpkg
```

**Comment by hunt3ri** [comment]
Thanks for implementing this, appreciated 👍
