### ISSUE TITLE
Failure to write tiles is silently ignored

### ISSUE THREAD

**Issue by jbg** [t-rex-tileserver/t-rex#61]
`Tile::write_to` and `Tile::write_gz_to` ignore the result of `CodedOutputStream::write_to`.

I ran out of inodes last night and kept generating tiles for 24h unaware that they were being thrown away as soon as they were generated!

I can send a patch - I was thinking it should log a warning if the tile is being saved from the web server, or abort if the tile is being saved from the "generate" process. What do you think?

**Comment by pka** [comment]
I think, this should be even logged as error. Probably it should give up after a certain number of errors, but that's a different thing. A pull request would be great!
Thanks for the feedback.
