### ISSUE TITLE
Self compiled version can not run on windows (gdal202.dll can not be found)

### ISSUE THREAD

**Issue by shanligang** [t-rex-tileserver/t-rex#62]
The latest compiled version can not run on windows.

**Comment by pka** [comment]
t-rex-v0.8.0.msi, right? What error message do you get when you run "%programfiles%\t-rex\t_rex" (with quotes) from the Command Prompt?

**Comment by simonokeefe** [comment]
It starts in Windows 10 OK for me.

```
C:\Users\Simon>"%programfiles%\t-rex\t_rex"
t_rex 0.8.0
Pirmin Kalberer <pka@sourcepole.ch>
vector tile server specialized on publishing MVT tiles from a PostGIS database

USAGE:
    t_rex [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    genconfig    Generate configuration template
    generate     Generate tiles for cache
    help         Prints this message or the help of the given subcommand(s)
    serve        Start web server and serve MVT vector tiles
```

**Comment by shanligang** [comment]
![image](https://user-images.githubusercontent.com/8465913/31010110-4a9db696-a53c-11e7-8937-0286e974a9f1.png)
I am using the latest version compiled with source code. When I go to run the compiled version of the above problem. "Can not continue to execute code because gdal202.dll can not be found"

**Comment by pka** [comment]
Ah, ok. Hints for compiling with GDAL support can be taken from https://github.com/t-rex-tileserver/t-rex/blob/master/appveyor.yml
To compile *without* GDAL support: `cargo build --no-default-features`

**Comment by shanligang** [comment]
![image](https://user-images.githubusercontent.com/8465913/31010771-928abfce-a53e-11e7-9959-486f54ccb3a4.png)

Ah..I'm sorry, I have a new problem.
"Can not continue to execute code because std-dd7c96bff832962e.dll can not be found"

**Comment by shanligang** [comment]
I feel that there may be rust crate problem

**Comment by shanligang** [comment]
![image](https://user-images.githubusercontent.com/8465913/31012293-dc54b36c-a543-11e7-96f8-81556291c2fb.png)
![image](https://user-images.githubusercontent.com/8465913/31012299-dff1fa66-a543-11e7-9623-b3224fef4efe.png)
The two components are updated today。

**Comment by shanligang** [comment]
![image](https://user-images.githubusercontent.com/8465913/31012345-0b7c008c-a544-11e7-9520-7e25f4f91fb4.png)

**Comment by pka** [comment]
The updated crates have compiled fine on AppVeyour: https://ci.appveyor.com/project/pka/t-rex/build/1.0.357
Maybe trying again after `cargo clean`?

**Comment by shanligang** [comment]
There is no problem with the compiler. But will run when the error.

**Comment by shanligang** [comment]
I was running two days ago when there is no problem, and today when running out of the problem.

**Comment by shanligang** [comment]
Hi.I have solved the problem。It turned out to be a GDAL version of the problem。
