### ISSUE TITLE
Layers from shapefiles not visible beyond initial zoom level

### ISSUE THREAD

**Issue by simonokeefe** [t-rex-tileserver/t-rex#63]
When attempting to use t-rex on my shapefiles, the layer appears in the map preview (Mapbox GL, OpenLayers, Maputnik, etc) at the initial zoom level, but when I attempt to zoom in, the layer is no longer visible.

(In comparison, when using the `natural_earth.gpkg` dataset, t-rex behaves as expected, and the layers remain visible at all zoom levels.)

The browser console shows that requests are made and PBF files are generated every time I zoom in, but nothing appears on the map. I get the same results with point, line and polygon shapefiles.

I've attached one of my shapefiles. I'm using t-rex 0.8.0 on Windows 10.

[Data.zip](https://github.com/t-rex-tileserver/t-rex/files/1353985/Data.zip)

**Comment by pka** [comment]
Hi Simon,
I can reproduce the problem with your sample data. Converting the shapefile from WGS 84 to Web-Mercator seems to solve the problem. Strangely enough I haven't the problem when doing on-the-fly reprojection with my own test shapefiles.

**Comment by pka** [comment]
There were two problems with this data:
1. t-rex didn't detect the shapefile SRS and assumed Web-Mercator. A warning is now emitted.
2. Bbox calculation for reprojected OGR geometries was wrong. Fixed in 6cade6b

**Comment by simonokeefe** [comment]
Thanks Pirmin.
