### ISSUE TITLE
Failed to send: the software in your host has stopped an established connection. (OS, error, 10053)

### ISSUE THREAD

**Issue by shanligang** [t-rex-tileserver/t-rex#65]
Failed to send: the software in your host has stopped an established connection. (OS, error, 10053)

**Comment by pka** [comment]
Looks like a Windows error message.  Is the problem reproducable? Do you have some log output before and after (ideally with `RUST_LOG=debug`)?

**Comment by shanligang** [comment]
![image](https://user-images.githubusercontent.com/8465913/31417059-dc5ed1ec-ae5f-11e7-83cf-4969db2c6401.png)

**Comment by pka** [comment]
I hope this is solved with the new built-in webserver. Please reopen if it's still happening with the coming version 0.9.0
