### ISSUE TITLE
Tile generation not honouring zoom level bounds?

### ISSUE THREAD

**Issue by Tom-Cuthill** [t-rex-tileserver/t-rex#67]
It appears that when we try to generate a tiles set, we are getting many more layers that we would expect.
Here is our generator command:

t_rex generate --config JustAsssets.conf --extent 12836528,-3913576,12993072,-3757032 --minzoom 8 --maxzoom 8 --overwrite true --progress true

In our JustAssets.conf file, we have layers defined like this:

[[tileset.layer]]
name = "node_lvoh_emtr"
table_name = "node_lvoh_emtr"
maxzoom = 16
minzoom = 16
geometry_field = "geom"
geometry_type = "POINT"
srid = 3857
fid_field = "FEATUREID"
buffer-size = 1
simplify = true

Note that this layer has a minimum and maximum zoom set to 16. I would not expect that the resulting tile would have this layer in it, but it does!

I've done my best to understand your code, but not knowing rust has me unsure about what happens in the prepare_queries method in postgis.rs.  My sense is that there are two ways the a query ends up in the queries btreemap.  In the top loop if the zoom level 8 is within the bounds of the layer's min and max zoom (16, and 16) which  isn't the case.  The other place is if there are gaps.  This part I'm not understanding:

let has_gaps = (layer.minzoom()..layer.maxzoom() + 1).any(|zoom | !queries.contains_key(&zoom));

Does this mean that if gaps are recognized if the layer's min and max zoom range contains the target zoom level or the btreemap of queries doesn't yet contain the zoom level?

I suspect that we are getting the query generated when we don't want it to be.

Any insights you can provide would be greatly appreciated.

Cheers,
Tom Cuthill

**Comment by Tom-Cuthill** [comment]
Hi,

I've rerun the generate with the log level set to trace and I can see that the node_lvoh_emtr layer is definitely being loaded when it shouldn't be:

2017-11-09 10:09:09.021 DEBUG executing query: BEGIN
2017-11-09 10:09:09.021 DEBUG executing statement s0 with parameters: [12836528.782099355, -3913575.848201027, 12993071.816027395, -3757032.8142729867]
2017-11-09 10:09:09.094 DEBUG Reading features in layer node_lvoh_emtr

I've done my best to understand the Rust code.  I can't see how the current situation arises, since the queries btree maps layer name to another btree map between the layer's zoom levels and their associated sql. Since the layer's zoom levels are what is used to generate the lower level btree map, the layers in question should not have an entry for zoom level 8, since the layer's TOML indicate that the minzoom and maxzoom are 16.

We are currently running t_rex on a CentOS machine and we are a few versions behind the current version.  Did something change in how the prepareQueries happened?  Is there any chance in getting a new version that we can run on CentOS?

Also I note that there is now a query_limit on each layer and that if it isn't specified, it defaults to 1000 features.  It is often the case that at the bottom of a zoom hierarchy the bottom level is densely packed to support overzooming.  For example, with the OSM tiles, at zoom level 14, it is common for tiles over cities to have many thousands of features in a layer (eg. buildings).  In our case, electrical utilities have thousands of point assets in some of our individual tiles.

I know that we can pre-read the table to figure out the total number of features and then try to estimate the top number of features per tile, but at best it will be a best guess and we could loose features due to the query_limit.

I suppose a wish-list for us would be if the generator would read the features in 1000 feature blocks.  That way memory would not be unbounded, and given that it could keep reading blocks until all the features are read, there would be no limit on the number of features in a layer.

Any suggestions you could offer would be greatly appreciated.

Cheers,
Tom Cuthill

**Comment by pka** [comment]
Hi Tom,

I did a first attempt to fix this, but it doesn't solve your issue. Currently `minzoom`/`maxzoom` is ignored at `tileset` and `tile` level. It's handled at `tile.query` level only! I'm still trying to figure out a proper configuration of tile **source** and **display** zoom limits (see https://github.com/mapbox/mapbox-gl-native/issues/9863#issuecomment-325615680). Ideas are welcome!

Feature count limit: features are not limited when `query_limit` isn't present in the configuration.  

Fetching in batches: Rows are fetched in batches (size 50) since 0.7.3.

Thanks for your feedback!

**Comment by pka** [comment]
Implementation finished in ceb19fa9e0656df3
