### ISSUE TITLE
Illegal character in connection string

### ISSUE THREAD

**Issue by sanfilippopablo** [t-rex-tileserver/t-rex#72]
Hello,
I have a `[` character in the password of my connection strings and the command returns this:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectParams(StringError("Illegal character in authority"))', /checkout/src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
I know that's the offending character because it works when I take it out (although I get authorization error obviously). I tried escaping it with `\` but it didn't work either.

**Comment by pka** [comment]
You have to percent-encode reserved charachters (https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters).
See also https://github.com/sfackler/rust-postgres/issues/306

**Comment by sanfilippopablo** [comment]
Thank you!
