### ISSUE TITLE
Display t-rex generated layer with mapbox baselayer

### ISSUE THREAD

**Issue by RemiDesgrange** [t-rex-tileserver/t-rex#81]
Didn't found any doc about it. What if I want to display data from t-rex server + a base layer from mapbox. (with mapboxgl)

I know about `addLayer` function with vector type, but you can only display 1 layer (and I cannot get it working tough...). What if I want to display 3,4,10 layers ? do I need to iterate ? Can we add `mapbox://XXXX` to the supported scheme so that we can add mapbox base layer to `style.json` file generated by t-rex ?

**Comment by RemiDesgrange** [comment]
Ok so if I read correctly:

There is not baselayer and overlay layer as opposed to raster display system (with leaflet for example). So the right way to do this is to do something like this:

```js
mapboxgl.accessToken = 'undefined';
var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/mapbox/streets-v9', // stylesheet location
    center: [-74.50, 40], // starting position [lng, lat]
    zoom: 9 // starting zoom
});
map.on('load', function(){
    map.addSource('t-rex-server', {
        type: "vector",
        url: "http://localhost:6767/my-tileset/tileset.json
    });
    const styles = [
         //download the style.json file via ajax for example 
     ]
     styles.forEach(function(s) {
         map.addLayer(s);
     });
}); 
```

Am I right ? You can close if you find this not appropriate

**Comment by pka** [comment]
You can combine layers programatically but you can also use a custom style json configuration. If you look at http://localhost:6767/my-tileset/tileset.style.json you see one source pointing to http://localhost:6767/my-tileset/tileset.json. You can create your custom style json with an additional source mapbox://styles/mapbox/streets-v9 as described in https://www.mapbox.com/mapbox-gl-js/style-spec#root-sources. If you use this style json in your Mapbox GL JS application, you can mix layers from both sources.
The built-in Maputnik editor also helps you to add additional sources, btw.

**Comment by RemiDesgrange** [comment]
I'm closing this.
