### ISSUE TITLE
Add support for reverse proxy

### ISSUE THREAD

**Issue by RemiDesgrange** [t-rex-tileserver/t-rex#83]
Right now if your server is `tile.example.com` t-rex will put in the json tileset definition : `http://tile.example.com:80/example/{z}/{x}/{y}.pbf` If I have a reverse proxy I will constantly make HTTP 302 redirect.

### Feature request :

add a "url" part in toml config file under `webserver`. 

@pka I'm total newbie in rust but if you can point me where to start I'll be happy to contribute :-)

**Comment by pka** [comment]
Does setting `baseurl` in the [cache section](http://t-rex.tileserver.ch/doc/reference/#cache) solve your problem?

**Comment by RemiDesgrange** [comment]
No, It doesn't work. Adding `baseurl` in the cache section doesn't change the url in json file (style and def).

**Comment by pka** [comment]
Your request didn't made it into 0.9.0, but with the new `static` option, you can serve your own json files along the automatically generated.

**Comment by pka** [comment]
Since 0.9.0 the hostname is resolved through the following headers, in this order:
* Forwarded
* X-Forwarded-Host
* Host
* Uri
* Server hostname

So, if the proxy is configured properly (i.e. passing X-Forwarded-Host), the metatdata should now include the proxy host name.
