### ISSUE TITLE
Consider using explicit dependencies 

### ISSUE THREAD

**Issue by lnicola** [t-rex-tileserver/t-rex#89]
It might be a good idea to specify the dependencies instead of using wildcards. I can put up a PR if you think it's worth it.

**Comment by pka** [comment]
I actually try to have as few versioned dependencies as possible. Encourages running `cargo update` more often. And when I don't have the time to fix compatibility problems, then I add a version dependency. Did this with rust-postgres a few times. But I'm absolutely open for other opinions!

**Comment by lnicola** [comment]
I think the trend has been to move away from wildcard dependencies for quite a while now. I've used them myself, but there are some reasons one might avoid them:

- publishing: crates with wildcard dependencies can't be published to `crates.io`
- image: some people start by looking at `Cargo.toml` when they see a crate and might think using wildcards is lazy
- documentation: more specific versions can better tell when the software was written, or when the dependency was evaluated last time
- updating: I found it somewhat easier to keep track of what's left when updating the dependencies one at a time
- maintenance: it's easier to check what new functionality a dependency has, in case one is inclined to read changelogs; with semver and appropriately-defined dependencies, `cargo update` should never break anything, so it's easier to separate low-effort updates from breaking changes
- pedantry: `*` dependencies are kinda' "wrong", as they mean "this will work with any version, at any time", which is certainly not the case

If you're worried about more churn on updates, you can simply use `foo = "1"`, or `foo = "1.2"` instead, which have the same effect.

But I admit, with the exception of the first one these are somewhat weak, in that `Cargo.lock`, `git log` and `cargo outdated` can answer the same questions.

**Comment by lnicola** [comment]
If you're still unconvinced, should we close this? :smile:

**Comment by pka** [comment]
I'm not really convinced, but fine with merging a PR, if contributors prefer that ;-)
