### ISSUE TITLE
Respect of Vector Tile Specification - Omit Empty Feature

### ISSUE THREAD

**Issue by frodrigo** [t-rex-tileserver/t-rex#91]
From https://github.com/mapbox/vector-tile-spec/tree/master/2.1#41-layers

> A Vector Tile SHOULD contain at least one layer. A layer SHOULD contain at least one feature.

A layer without feature should be omitted.
A tile without layer should be omitted (HTTP 404).

If you agree I may try implement it.

**Comment by pka** [comment]
Wasn't aware of that. A PR would be great!
