### ISSUE TITLE
Respect of Vector Tile Specification - Omit empty file in cache

### ISSUE THREAD

**Issue by frodrigo** [t-rex-tileserver/t-rex#96]
After #91 and #94 There is still a missing part.

The cache store empty files (valid pdf for no content) as gzip'ed files. So the cache store 0 byte file size as 20 byte file size.

I don't know if the cache is only for dump or used also to serve tile in http.
No idea yet on how to cache empty tiles as nothing...

**Comment by pka** [comment]
With 176f7c7, tiles outside of tileset min-/maxzoom are not stored in cache anymore and 404 is returned. I've added a TODO  in the code for handling remaining empty tiles.

**Comment by pka** [comment]
With 67f3ce8, empty tiles are not stored in cache anymore. This has the disadvantage that empty tiles are recalculated on each request in live mode, but gives a correct 404 when served by a web server from a static tile cache.
