### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by diskmanti** [t-rex-tileserver/t-rex#97]
t_rex server has gone through a lot of changes. It would be nice to have some more examples on the document page to show all the features. For example how to set up t_rex to read from geopackages or other gdal sources. The docs do not show how this can be set up very nicely.

**Comment by pka** [comment]
There are a few additional usage examples in the latest slides referenced in README.md. They should be usable for the documentation in https://github.com/t-rex-tileserver/t-rex-website/ as well.

**Comment by diskmanti** [comment]
Is there a way to use the genconfig command for a GeoPackage database?

**Comment by pka** [comment]
Example:
`t_rex genconfig --datasource data/avch.gpkg`

**Comment by diskmanti** [comment]
Thank you for the response and the awesome project you have put together. ☺

**Comment by pka** [comment]
I've added some examples here: https://t-rex.tileserver.ch/doc/serve/
