### ISSUE TITLE
Around the antimeridian

### ISSUE THREAD

**Issue by waigania13** [t-rex-tileserver/t-rex#98]
I am distributing natural earth data from postgis using t-rex.
Self-intersection error occurs only tiles that near antimeridian.
t-rex made SQL like following,

> SELECT ST_Transform(ST_Multi(ST_Buffer(ST_Intersection(ST_MakeValid(geom),ST_Transform(ST_Buffer(ST_MakeEnvelope(-20037508.3427892,7514065.62854596,-17532819.7999406,10018754.1713946,3857),10*9783.93962050256),4326)), 0.0)),3857) AS shape,"gid" FROM (    SELECT
>         gid,
>         shape
>         FROM ne_10m_admin_0_countries
>         WHERE geom && ST_Transform(ST_Buffer(ST_MakeEnvelope(-20037508.3427892,7514065.62854596,-17532819.7999406,10018754.1713946,3857),10*9783.93962050256),4326)
>         ) AS _q

If I add ST_Shift_Longitude(), I can avoid errors.

> SELECT ST_Transform(ST_Multi(ST_Buffer(ST_Intersection(ST_MakeValid(geom),ST_Shift_Longitude(ST_Transform(ST_Buffer(ST_MakeEnvelope(-20037508.3427892,7514065.62854596,-17532819.7999406,10018754.1713946,3857),10*9783.93962050256),4326))), 0.0)),3857) AS shape,"gid" FROM (    SELECT
>         gid,
>         shape
>         FROM ne_10m_admin_0_countries
>         WHERE geom && ST_Transform(ST_Buffer(ST_MakeEnvelope(-20037508.3427892,7514065.62854596,-17532819.7999406,10018754.1713946,3857),10*9783.93962050256),4326)
>         ) AS _q

Do you have any idea avoid this kind error?

**Comment by pka** [comment]
Added your `ST_Shift_Longitude` fix for transformed envelopes in fbf0d36.
Thanks for your feedback!
