### ISSUE TITLE
Styling the OSM

### ISSUE THREAD

**Issue by michaelknave** [t-rex-tileserver/t-rex#99]
How do you solve the styling of OSM vector tiles. 

What tool do you use for importing to the database? And how do you configure styling ? 

I am using osm2pgsql and import .osm.pbf file into the table structure - planet_osm_line, planet_osm, point, planet_osm_polygon, planet_osm_road. 

Am I able to configure .toml file to display osm in nice style (e.g. something like osm-bright) ?

**Comment by pka** [comment]
There is an example https://github.com/t-rex-tileserver/t-rex/blob/master/examples/osm2vectortiles.toml using the osm2vectortiles (now OpenMapTiles) import schema. On their Github repos you'll also find styles similar to osm-bright. My advise is to use Mapbox GL JSON styling and use t-rex to generate the approprite vector tiles. For styling you can use the built-in Maputnik tool and export the styles from there.

**Comment by michaelknave** [comment]
I have already checked that, but there is still issue that current import schema (using imposm3 tool) from openmaptiles is different than schema in 
https://github.com/t-rex-tileserver/t-rex/blob/master/examples/osm2vectortiles.toml . 

E.g. in current import schema for vector tiles, there is separate table for each zoom lvl. In mentioned .toml config, there is not.

**Comment by pka** [comment]
Were you able to adapt the t-rex config to the newer schema or did you encounter a limitation in t-rex?
